### PR TITLE
Added count of ratings.

### PR DESCRIPTION
**Pull request by Vedant-Gandhi**
I have added the count of ratings which is independent of the number of rating

### CODE REVIEW

**Comment by sav-norem** [comment]
Great! It’s a holiday weekend for me but wanted to let you know I’ll check it out first thing tomorrow!

**Comment by SuzeShardlow** [comment]
Closes #4 when merged.

**Comment by SuzeShardlow** [comment]
@Vedant-Gandhi thanks for the PR!  If you are a member of the Redis Discord server (https://discord.gg/redis), please let us know your handle and we will give you the `Hacktoberfest 2022` role.  Thanks!

**Comment by Vedant-Gandhi** [comment]
@SuzeShardlow Sorry didn't see your comment. I am a member of Redis Discord Server. Here is my username - Vedant#5658

**Comment by SuzeShardlow** [comment]
Thanks @Vedant-Gandhi!  I've given you the role in Discord :)

**Comment by Vedant-Gandhi** [comment]
Cool

**Pull request merged**
